export type Status='draft'|'pending'|'in_progress'|'approved'|'rejected'|'returned'|'cancelled'|'orphaned';
export type Action='submitted'|'approved'|'rejected'|'returned'|'cancelled';
export interface Request {id:number; status:Status; currentStep:number; currentApprovers:number[]; version:number; submittedBy:number; [key:string]:any}
export interface Step {id:number; stepOrder:number; approverType:string; approverConfig:any; mode?:string; completionRule?:'all'|'any'; [key:string]:any}
export interface ApprovalRepository { getRequest(id:number,tx?:any):Promise<Request>; getSteps(templateId:number,version:number,tx?:any):Promise<Step[]>; resolveApprovers(step:Step,request:Request,tx?:any):Promise<number[]>; updateRequest(id:number,patch:any,where?:any,tx?:any):Promise<boolean>; addAction(data:any,tx?:any):Promise<any>; countActions?(requestId:number,stepId:number,action:Action,tx?:any):Promise<number>; snapshot(data:any,tx?:any):Promise<any>; nextRequestNo(tx?:any):Promise<string>; transaction<T>(fn:(tx:any)=>Promise<T>):Promise<T>; notify?(users:number[],event:string,request:Request):Promise<void>; }
export class ApprovalError extends Error { constructor(public code:string,message:string){super(message);this.name='ApprovalError'} }
const msg={unauthorized:'You are not authorized to approve this request.',processed:'This request has already been processed.',step:'This approval step is no longer active.',approver:'No approver could be resolved.'};
export class ApprovalEngine {
 constructor(private repo:ApprovalRepository, private logger: any = console) {}
 async submit(input:{templateId:number;templateVersion:number;targetCollection:string;targetRecordId:string;submittedBy:number;snapshot:any;steps?:Step[]}):Promise<any>{return this.repo.transaction(async tx=>{const steps=input.steps||await this.repo.getSteps(input.templateId,input.templateVersion,tx);if(!steps.length)throw new ApprovalError('NO_STEPS','Approval template has no active steps.');const first=steps.sort((a,b)=>a.stepOrder-b.stepOrder)[0];const approvers=await this.repo.resolveApprovers(first,input as any,tx);if(!approvers.length)throw new ApprovalError('NO_APPROVER',msg.approver);const no=await this.repo.nextRequestNo(tx);const r:any={requestNo:no,templateId:input.templateId,templateVersion:input.templateVersion,targetCollection:input.targetCollection,targetRecordId:input.targetRecordId,submittedBy:input.submittedBy,status:'in_progress',currentStep:first.stepOrder,currentApprovers:approvers,version:0,submittedAt:new Date()};const created=await this.repo.updateRequest(0,r,undefined,tx);await this.repo.snapshot({requestId:created.id,snapshotData:input.snapshot},tx);await this.repo.addAction({requestId:created.id,stepId:first.id,actorId:input.submittedBy,action:'submitted'},tx);await this.repo.notify?.(approvers,'new_approval',created);this.logger.info?.('Approval request created', {requestNo:no});return created;});}
 async act(id:number,actorId:number,action:'approved'|'rejected'|'returned'|'cancelled',comment?:string):Promise<any>{return this.repo.transaction(async tx=>{const r=await this.repo.getRequest(id,tx);if(!['pending','in_progress'].includes(r.status))throw new ApprovalError('PROCESSED',msg.processed);if(action==='cancelled'){await this.repo.updateRequest(id,{status:'cancelled'}, {version:r.version,status:r.status},tx);await this.repo.addAction({requestId:id,actorId,action:'cancelled',comment},tx);return this.repo.getRequest(id,tx)}if(!r.currentApprovers.includes(actorId))throw new ApprovalError('UNAUTHORIZED',msg.unauthorized);if(action==='rejected'||action==='returned'){if(!comment?.trim())throw new ApprovalError('REASON_REQUIRED','A reason is required.');const status=action==='rejected'?'rejected':'returned';await this.repo.updateRequest(id,{status,[action==='rejected'?'rejectionReason':'returnReason']:comment,version:r.version+1}, {version:r.version},tx);await this.repo.addAction({requestId:id,stepId:r.currentStep,actorId,action,comment},tx);await this.repo.notify?.([r.submittedBy],action,r);return this.repo.getRequest(id,tx)}
 const steps=await this.repo.getSteps(r.templateId,r.templateVersion,tx);const current=steps.find(s=>s.stepOrder===r.currentStep);if(!current)throw new ApprovalError('STEP',msg.step);await this.repo.addAction({requestId:id,stepId:current.id,actorId,action:'approved',comment},tx);const previous=await this.repo.getRequest(id,tx);const done=current.completionRule==='any'||(current.completionRule==='all'&&false);const actions:any[]=[]; /* repository may provide aggregate in a future adapter */
 if(current.completionRule==='all' && r.currentApprovers.length>1){const count=await this.repo.countActions?.(id,current.id,'approved',tx)??0;if(count<r.currentApprovers.length)return this.repo.getRequest(id,tx);}
 const nextStep=steps.filter(s=>s.active!==false&&s.stepOrder>current.stepOrder).sort((a,b)=>a.stepOrder-b.stepOrder)[0];if(!nextStep){await this.repo.updateRequest(id,{status:'approved',completedAt:new Date(),version:r.version+1},{version:r.version},tx);await this.repo.notify?.([r.submittedBy],'approved',r);return this.repo.getRequest(id,tx)}const aps=await this.repo.resolveApprovers(nextStep,r,tx);if(!aps.length)throw new ApprovalError('NO_APPROVER',msg.approver);await this.repo.updateRequest(id,{status:'in_progress',currentStep:nextStep.stepOrder,currentApprovers:aps,version:r.version+1},{version:r.version},tx);await this.repo.notify?.(aps,'new_approval',r);return this.repo.getRequest(id,tx);});}
}
